#1 [internal] load build definition from Dockerfile
#1 sha256:20a6c8d4294039abc3b04bfc34e5c8fa144ecd80a2ccf81b2935fb8fb4bd01d1
#1 transferring dockerfile: 628B 0.0s done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:1e393b10a1c6b1d792950ec9839f46db7dcbada56e9d32df5eb8d300ca14fddf
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.12
#3 sha256:36e2c455b1b565127e04502006ec81799d2000c65da49d843f1d8e154f29a3ee
#3 DONE 1.5s

#4 [1/7] FROM docker.io/library/python:3.12@sha256:e83d1f4d0c735c7a54fc9dae3cca8c58473e3b3de08fcb7ba3d342ee75cfc09d
#4 sha256:fefcc06c8388b83d0956c576c44c3040eaaf31335112f3bbae13d459cb69151a
#4 DONE 0.0s

#6 [internal] load build context
#6 sha256:4d78b1c8b63e52a29c61c0fad777bbb21ad1395f7d7c212f3a84261713d32186
#6 transferring context: 25.12kB 0.0s done
#6 DONE 0.0s

#5 [2/7] WORKDIR /usr/src/app
#5 sha256:3424e31debf25cccc06fc361ed3dac56a0a6a19f93e8cb5863adfdcc3af7d8cc
#5 CACHED

#7 [3/7] COPY . /usr/src/app
#7 sha256:dc1be3e88fa14a781b263567bc81bb8d1a647d2aab5ba54c4d3deac215966368
#7 DONE 0.0s

#8 [4/7] RUN pip install --upgrade pip
#8 sha256:5f7c71320c85ee0eeb072a9b4c45a7d9dbb40ebfdfffb96a3003de1db034e6ff
#8 1.056 Requirement already satisfied: pip in /usr/local/lib/python3.12/site-packages (24.0)
#8 1.173 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#8 DONE 1.3s

#9 [5/7] RUN pip install pytest
#9 sha256:ee0fc04691ac2e70beb5615b3009da51f1c4b85cdedfd8796af81f0aa6a16fd3
#9 0.408 Collecting pytest
#9 0.496   Downloading pytest-8.0.2-py3-none-any.whl.metadata (7.7 kB)
#9 0.531 Collecting iniconfig (from pytest)
#9 0.543   Downloading iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
#9 0.567 Collecting packaging (from pytest)
#9 0.580   Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
#9 0.605 Collecting pluggy<2.0,>=1.3.0 (from pytest)
#9 0.616   Downloading pluggy-1.4.0-py3-none-any.whl.metadata (4.3 kB)
#9 0.642 Downloading pytest-8.0.2-py3-none-any.whl (333 kB)
#9 0.685    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 334.0/334.0 kB 7.8 MB/s eta 0:00:00
#9 0.700 Downloading pluggy-1.4.0-py3-none-any.whl (20 kB)
#9 0.720 Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
#9 0.736 Downloading packaging-23.2-py3-none-any.whl (53 kB)
#9 0.746    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 6.5 MB/s eta 0:00:00
#9 0.780 Installing collected packages: pluggy, packaging, iniconfig, pytest
#9 0.964 Successfully installed iniconfig-2.0.0 packaging-23.2 pluggy-1.4.0 pytest-8.0.2
#9 0.965 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 DONE 1.0s

#10 [6/7] RUN pip install -e .
#10 sha256:3b6734534b229e94508fa42c2d3ecb89f81883d7530fdaa0004d83cda77ab033
#10 0.487 Obtaining file:///usr/src/app
#10 0.488   Installing build dependencies: started
#10 1.468   Installing build dependencies: finished with status 'done'
#10 1.469   Checking if build backend supports build_editable: started
#10 1.553   Checking if build backend supports build_editable: finished with status 'done'
#10 1.554   Getting requirements to build editable: started
#10 1.635   Getting requirements to build editable: finished with status 'done'
#10 1.637   Preparing editable metadata (pyproject.toml): started
#10 1.732   Preparing editable metadata (pyproject.toml): finished with status 'done'
#10 1.736 Building wheels for collected packages: prime_factors
#10 1.736   Building editable for prime_factors (pyproject.toml): started
#10 1.837   Building editable for prime_factors (pyproject.toml): finished with status 'done'
#10 1.837   Created wheel for prime_factors: filename=prime_factors-0.0.1-0.editable-py3-none-any.whl size=2320 sha256=049d6fa39c79c11166fad18d21e166d0c3876a49e9632405df51214747d47815
#10 1.837   Stored in directory: /tmp/pip-ephem-wheel-cache-5p1c_s5m/wheels/a0/61/be/78acd02a6cc5452ae32b0da11bd4898cac12e447cdbe89da8a
#10 1.839 Successfully built prime_factors
#10 1.867 Installing collected packages: prime_factors
#10 1.871 Successfully installed prime_factors-0.0.1
#10 1.871 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#10 DONE 1.9s

#11 [7/7] RUN git apply diff_patch.patch
#11 sha256:aa3df8ab479fc4cba09572913697284911494f00d8904a002f9c5fa5570189b7
#11 0.288 error: can't open patch 'diff_patch.patch': No such file or directory
#11 ERROR: executor failed running [/bin/sh -c git apply diff_patch.patch]: exit code: 128
------
 > [7/7] RUN git apply diff_patch.patch:
------
executor failed running [/bin/sh -c git apply diff_patch.patch]: exit code: 128
